apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: dev
spec:
  encryptedData:
    password: AgB0A8jttg+lPsBUyoQfmq0lGUkGQPx8Nl/JmlUAjpYFU4vO5OSE5UECwzrH0FQvwkz30IarvSqq9eosSBPVxfmfOBR9xDPzNdjTm0oznU3IAoF6crAWcAOAz5W/NsA0u82SShklEC5aaOXxXy027+yDzmFSLzxKcZZ12khuBtoR3xvAp7M3wCDGrMCiOoIL3NhSPUm0sOTJ8Pcm3AdjORhweJ+wInsIuTk1a3cA+zQJmPW+NwvrMUpUwgUFz8WP7NqZHuYon+a2nmipHmm9OAR74ZW1oA2RGwb65U2IWkNwftop4Kj/c+G/91FaxI+iezdQJK6m6AWdkv7wU+f9WFHv4jd5SllzUg3HjpojmMs2K4M4X0NMyffj//rQGzVrGBv4eqpnXJCthEhJZ/YIG/L7SUBXbWfhaXRytBFTnT950gMOT9IgWw07fi4FwVrxpIPMcukA6ORBnmfb8q6eqBZaCLPH/8yoArA8yejj+BWA/q9TpbKhZo3LEH02RljKytRMOLh6Up+5j7RPfpK1UnvgUG/TlI6iLzgDdMs+EuEN0v8W2sLjXGMepe5Ei4oTLyyvDJOasPjLO+++UWAHRbrwDC+C8Ir7673WBjeJGsXtZRN4TGjRA5gxDY9Ggrb/kdpS6VG26cvgaq3zct+7SdmPGmJ4n/5MXCLJoUt+TSDZn/FNO8zD8xwcOfeksxRKIM2enE/KmQ==
    user: AgAevAGHzIlc54Qcop2fB7VlHdfnEP16/htGc8G/BU2qrbg99MZ0qrFry9MlSB29TjYOtAu7uL6dHc+WBDKByy5bWourPQSkRyrwTynzZsFhe1GrUgsrzqjSlJl2c0UGawWi0zZvhwIbklFyYaV5HRhCxC5PkFAsoHGEr50mP+bOlu3F2oX630D1J+ZA2RWN/nEmqTqbuyC5dpchstT74nU4UxLdeEMnwHwVBxAi0qp0eHjFQt+tWFPq6St+9bGGRVSY4hsMNjEDqArgxUIcDd8falApGzP6lRYGhJIWdMvx51+LQln36dseWiPOTeNkLA1aP7Do9NCJSawWwr72Hgp6EdAt/otmFahKJhDAoUVpDx6PrELCvP8gP8CfIqPs5QF41E7fRXVPL11voMgJ7iPQ1UWgbDDxrpBBr4gKXI4CEKPm5is5LJ8aMjjeSMHj8L3cyUZfdTxfOJUQLJNMXpDa65AgVtAS5bRFq1ePQmGjzF1N0ykr8v8yVDHRJthe2Jshv7aecmh7yDNevKlhSbeIckqiJk+f+pCtWMQHGWsFg7bHgPHIPirl1pXLrG5VRyzlgVqT+qfUAxJzEEnUcwGIF4tPpv1BuBgGLtH8NpggtKokzksXs4GQStWuz7xlvzeuHnzesuE0SgTgeCv7MSrFpRj+tDdgnxEHx3e+AjWhMqj+qtlt6LcAvFQF0BFkqdHa2kmFPA==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: dev

